module.exports = {
    ru: {
        "nav_f": 'О сервисе',
        "nav_t": 'Как это работает',
        "send_req": 'Отправить заявку',
        "heading": 'Сервис автоматизации для работы с отзывами <br> в Google Play',
        "page_desc": "Replyme – это нейросеть, которая отвечает на отзывы пользователей и oсуществляет их сортировку. Оставьте рутиную работу сервису и освободите свое время и ресурсы.",
        "why_work": 'Как работает сервис',
        "sorty": 'Сортировка отзывов',
        "sorty_t": 'На отзывы, не требующие вашего участия, сервис отвечает самостоятельно. Отзывы о проблемах Replyme моментально передает команде разработчиков',
        "details": 'Детали работы',
        "details_t": 'Replyme работает с Google Play. Сервис поддерживает русский и английский язык.<br>Работает 24/7',
        "pr": 'Преимущества',
        "pr_t": 'Replyme значительно дешевле, чем техподдержка. Актуальная информация по отзывам всегда под рукой',
        "order_service": 'Заказать сервис',
        "order_service_text": 'Напишите нам, указав свои контактные данные. С вами свяжется наш менеджер для уточнения деталей',
        "name": "Имя",
        "user_name_f": "Dovilnyi Polzovatel",
        "user_comment_f": "Отзывы пишу редко. Но тут решил написать. Отличное приложение, удобное и простое.",
        "reply": "Auto Support",
        "reply_comment_f": "Привет! Спасибо за хороший отзыв! Ваши Ваши слова вдохновляют <span class='reviews__smile'></span>",
        "user_name_t": "Nedovilnyi",
        "user_comment_t": "Хорошая идея, но есть недочеты. При входе требует пароль, но мой пароль не принимает, хотя я все проверил",
        "reply_comment_t": "Привет! Спасибо за отзыв! Мы читаем и анализируем все  комментарии, поэтому фидбек будет очень полезен."
    },
    en: {
        "nav_f": 'About the service',
        "nav_t": 'How it works',
        "send_req": 'Sign up',
        "heading": 'Automation service to process reviews <br> on Google Play',
        "page_desc": "Replyme is a neural network that responds to user reviews and sorts them. Leave the routine work to the service and free up your time and resources.",
        "why_work": 'How the service works',
        "sorty": 'Sorting reviews',
        "sorty_t": 'The service automatically responds to reviews that do not require your personal attention. At the same time Replyme instantly sends feedback on issues to the development team.',
        "details": 'Service details',
        "details_t": 'Replyme works with Google Play.<br> The service is available in Russian and English languages.<br> It works 24/7.',
        "pr": 'Benefits',
        "pr_t": 'Replyme is significantly cheaper than using tech support. Up-to-date information on reviews is always at hand.',
        "order_service": 'Sign up for the service',
        "order_service_text": 'Sign up by sending us your contact details. Our manager will contact you shortly.',
        "name": "Name",
        "user_name_f": "Satisfied user",
        "user_comment_f": "I rarely write reviews, but I've decided to leave one this time. Great app, user-friendly and intuitive. <span class='reviews__smile'></span>",
        "reply": "Reply",
        "reply_comment_f": "Hi! Thanks for a positive review! We're happy you liked our app!",
        "user_name_t": "Dissatisfied user",
        "user_comment_t": "I like the idea, but there are some drawbacks. It requires you to enter your password to log in, but it just doesn't accept my password, although I made sure it was correct.",
        "reply_comment_t": "Hi! Thanks for your review! We read and analyze all comments, so we appreciate any feedback you can give us."
    }
}
